# Generated by Django 5.0 on 2023-12-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.PositiveIntegerField(default=123, unique=True),
        ),
    ]
