# Generated by Django 5.0 on 2023-12-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
