# Generated by Django 5.0 on 2023-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=100),
        ),
    ]
